// EventTypes.js
// Fichier centralisant tous les types d'événements utilisés dans l'application
window.EVENTS = {
  INPUT: {
    KEYDOWN: 'INPUT_KEYDOWN',
    KEYUP: 'INPUT_KEYUP',
    KEYPRESS: 'INPUT_KEYPRESS',
    WHEEL: 'INPUT_WHEEL',
    MOUSEDOWN: 'INPUT_MOUSEDOWN',
    MOUSEMOVE: 'INPUT_MOUSEMOVE',
    MOUSEUP: 'INPUT_MOUSEUP',
    TOUCHSTART: 'INPUT_TOUCHSTART',
    TOUCHMOVE: 'INPUT_TOUCHMOVE',
    TOUCHEND: 'INPUT_TOUCHEND',
    GAMEPAD_CONNECTED: 'INPUT_GAMEPAD_CONNECTED',
    GAMEPAD_DISCONNECTED: 'INPUT_GAMEPAD_DISCONNECTED',
    JOYSTICK_AXIS_CHANGED: 'INPUT_JOYSTICK_AXIS_CHANGED',
    JOYSTICK_AXIS_HELD: 'INPUT_JOYSTICK_AXIS_HELD',
    JOYSTICK_AXIS_RELEASED: 'INPUT_JOYSTICK_AXIS_RELEASED',
    JOYSTICK_BUTTON_DOWN: 'INPUT_JOYSTICK_BUTTON_DOWN',
    JOYSTICK_BUTTON_UP: 'INPUT_JOYSTICK_BUTTON_UP',
    KEYMAP_CHANGED: 'INPUT_KEYMAP_CHANGED',
    KEYMAP_RESET: 'INPUT_KEYMAP_RESET'
  },
  PHYSICS: {
    UPDATED: 'PHYSICS_UPDATED',
    COLLISION: 'PHYSICS_COLLISION'
  },
  RENDER: {
    UPDATE: 'RENDER_UPDATE',
    TOGGLE_VECTORS: 'RENDER_TOGGLE_VECTORS',
    TOGGLE_GRAVITY_FIELD: 'RENDER_TOGGLE_GRAVITY_FIELD'
  },
  SIMULATION: {
    UPDATED: 'SIMULATION_UPDATED'
  },
  UI: {
    UPDATE: 'UI_UPDATE'
  },
  ROCKET: {
    STATE_UPDATED: 'ROCKET_STATE_UPDATED'
  },
  UNIVERSE: {
    STATE_UPDATED: 'UNIVERSE_STATE_UPDATED'
  },
  PARTICLE_SYSTEM: {
    UPDATED: 'PARTICLE_SYSTEM_UPDATED'
  }
}; 